# Generated by Django 2.1.4 on 2019-01-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
    ]
