# Generated by Django 2.1.4 on 2019-01-03 23:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190103_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.work_image_file_path),
        ),
    ]
