# Generated by Django 2.1.5 on 2019-01-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190108_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='work',
            name='tags',
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
