# Generated by Django 2.1.5 on 2019-01-10 21:18

from django.db import migrations
import os
import csv

#Locate csv file to import
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CAT_FILE = os.path.join(BASE_DIR, 'art_data.csv')

def insert_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    categories = list(Category.objects.all().values_list('name', flat=True))
    with open(CAT_FILE, mode='r') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            if row['classification'] not in categories:
                Category.objects.create(name=row['classification'])
                categories.append(row['classification'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190109_2235'),
    ]

    operations = [
        migrations.RunPython(insert_categories)
    ]
