# Generated by Django 2.1.5 on 2019-01-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190110_insert_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='imagecredit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
